<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*$data = array (
		  0 => 
		  array (
		    'id' => 1,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'bidang',
		    'display_name' => 'Bidang',
		    'content' => 'Bidang Geoteknik',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  1 => 
		  array (
		    'id' => 2,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'tempat-lahir',
		    'display_name' => 'Tempat Lahir',
		    'content' => 'Banda Aceh',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  2 => 
		  array (
		    'id' => 3,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'tgl-lahir',
		    'display_name' => 'Tgl Lahir',
		    'content' => '2020-06-01',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  3 => 
		  array (
		    'id' => 4,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'agama',
		    'display_name' => 'Agama',
		    'content' => 'Islam',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  4 => 
		  array (
		    'id' => 5,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'gender',
		    'display_name' => 'Gender',
		    'content' => 'Laki-laki',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  5 => 
		  array (
		    'id' => 6,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'no-hp',
		    'display_name' => 'No Hp',
		    'content' => '085208520852',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  6 => 
		  array (
		    'id' => 7,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'email',
		    'display_name' => 'Email',
		    'content' => 'test@test.com',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  7 => 
		  array (
		    'id' => 8,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'judul-tga',
		    'display_name' => 'Judul Tga',
		    'content' => 'Test',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  8 => 
		  array (
		    'id' => 9,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'tahun-ajaran',
		    'display_name' => 'Tahun Ajaran',
		    'content' => '2018/2019',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  9 => 
		  array (
		    'id' => 10,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'dosen-wali',
		    'display_name' => 'Dosen Wali',
		    'content' => 'Dr. Ir. Abdullah, M.Sc.',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  10 => 
		  array (
		    'id' => 11,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'ketua-bidang',
		    'display_name' => 'Ketua Bidang',
		    'content' => 'Devi Sundary, S.T., M.T.',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  11 => 
		  array (
		    'id' => 12,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'dana-pendidikan',
		    'display_name' => 'Dana Pendidikan',
		    'content' => 'Biaya Sendiri',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  12 => 
		  array (
		    'id' => 13,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'file',
		    'name' => 'spp',
		    'display_name' => 'Spp',
		    'content' => '1104101010001-spp.pdf',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  13 => 
		  array (
		    'id' => 14,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'file',
		    'name' => 'krs',
		    'display_name' => 'Krs',
		    'content' => '1104101010001-krs.pdf',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  14 => 
		  array (
		    'id' => 15,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'file',
		    'name' => 'transkrip-sementara',
		    'display_name' => 'Transkrip Sementara',
		    'content' => '1104101010001-transkrip-sementara.pdf',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  15 => 
		  array (
		    'id' => 16,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'file',
		    'name' => 'khs',
		    'display_name' => 'Khs',
		    'content' => '1104101010001-khs.pdf',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  16 => 
		  array (
		    'id' => 17,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'file',
		    'name' => 'foto',
		    'display_name' => 'Foto',
		    'content' => '1104101010001-foto.png',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 15:40:28',
		    'updated_at' => '2020-06-26 16:00:07',
		  ),
		  17 => 
		  array (
		    'id' => 19,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'co-pembimbing',
		    'display_name' => 'Nama Co Pembimbing',
		    'content' => 'Ir. Banta Chairullah M, M.Ing.',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 16:01:26',
		    'updated_at' => '2020-06-26 16:02:28',
		  ),
		  18 => 
		  array (
		    'id' => 18,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'text',
		    'name' => 'pembimbing',
		    'display_name' => 'Nama Pembimbing',
		    'content' => 'Dr. Ir. Abdullah, M.Sc.',
		    'no' => NULL,
		    'tgl' => NULL,
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 16:01:26',
		    'updated_at' => '2020-06-26 16:02:45',
		  ),
		  19 => 
		  array (
		    'id' => 20,
		    'user_id' => 68,
		    'category' => 'data_usul',
		    'type' => 'file',
		    'name' => 'sk-pembimbing',
		    'display_name' => 'SK Penunjukan Pembimbing',
		    'content' => '1104101010001-sk-pembimbing.pdf',
		    'no' => '1/TA/II/2020',
		    'tgl' => '2020-06-26',
		    'verified' => 'true',
		    'verification_key' => NULL,
		    'created_at' => '2020-06-26 16:48:24',
		    'updated_at' => '2020-06-26 17:35:57',
		  ),
		);

		foreach ($data as $index => $value) {
			DB::table('data')->insert([
				'user_id' => $value['user_id'],
				'category' => $value['category'],
				'type' => $value['type'],
				'name' => $value['name'],
				'display_name' => $value['display_name'],
				'content' => $value['content'],
				'no' => $value['no'],
				'tgl' => $value['tgl'],
				'verified' => $value['verified'],
				'verification_key' => $value['verification_key'],
				'created_at' => $value['created_at'],
				'updated_at' => $value['updated_at']
			]);
		}*/
    }
};
