<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
			array(
				"id" => 74,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "draft-buku-tga",
				"display_name" => "Draft Buku TGA",
				"content" => "1104101010001-draft-buku-tga.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 12:29:25",
				"updated_at" => "2020-06-29 16:15:53",
			),
			array(
				"id" => 1,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "bidang",
				"display_name" => "Bidang",
				"content" => "Bidang Geoteknik",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 2,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "tempat-lahir",
				"display_name" => "Tempat Lahir",
				"content" => "Banda Aceh",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 3,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "tgl-lahir",
				"display_name" => "Tgl Lahir",
				"content" => "2020-06-01",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 4,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "agama",
				"display_name" => "Agama",
				"content" => "Islam",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 5,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "gender",
				"display_name" => "Gender",
				"content" => "Laki-laki",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 6,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "no-hp",
				"display_name" => "No Hp",
				"content" => "085208520852",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 7,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "email",
				"display_name" => "Email",
				"content" => "diva.mujaddidi@outlook.com",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 8,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "judul-tga",
				"display_name" => "Judul Tga",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 9,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "tahun-ajaran",
				"display_name" => "Tahun Ajaran",
				"content" => "2018/2019",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 10,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "dosen-wali",
				"display_name" => "Dosen Wali",
				"content" => "Dr. Ir. Abdullah, M.Sc.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 11,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "ketua-bidang",
				"display_name" => "Ketua Bidang",
				"content" => "Devi Sundary, S.T., M.T.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-07-03 20:28:47",
			),
			array(
				"id" => 12,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "dana-pendidikan",
				"display_name" => "Dana Pendidikan",
				"content" => "Biaya Sendiri",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:30",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 13,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "spp",
				"display_name" => "Spp",
				"content" => "1104101010001-spp.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:31",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 14,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "krs",
				"display_name" => "Krs",
				"content" => "1104101010001-krs.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:31",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 15,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "transkrip-sementara",
				"display_name" => "Transkrip Sementara",
				"content" => "1104101010001-transkrip-sementara.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:31",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 16,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "khs",
				"display_name" => "Khs",
				"content" => "1104101010001-khs.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:31",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 17,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "foto",
				"display_name" => "Foto",
				"content" => "1104101010001-foto.jpeg",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 14:51:31",
				"updated_at" => "2020-06-27 14:55:12",
			),
			array(
				"id" => 21,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "sptpd",
				"display_name" => "Surat Permohonan Tugas Pengambilan Data",
				"content" => "1104101010001-sptpd.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 15:11:47",
				"updated_at" => "2020-07-05 10:02:18",
			),
			array(
				"id" => 53,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "tgl-seminar",
				"display_name" => "Tanggal Seminar",
				"content" => "2020-07-28",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-28 15:10:14",
				"updated_at" => "2020-07-05 10:28:09",
			),
			array(
				"id" => 57,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "berkas-seminar-lainnya",
				"display_name" => "Berkas Seminar Lainnya",
				"content" => "1104101010001-berkas-seminar-lainnya.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-28 18:33:23",
				"updated_at" => "2020-06-30 12:03:25",
			),
			array(
				"id" => 55,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "sk-penguji-sempro",
				"display_name" => "SK Penguji Sempro",
				"content" => "1104101010001-sk-penguji-sempro.pdf",
				"no" => "1/TA/II/2020",
				"tgl" => "2020-06-28",
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-28 18:33:23",
				"updated_at" => "2020-06-30 12:03:25",
			),
			array(
				"id" => 20,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "sk-pembimbing",
				"display_name" => "SK Penunjukan Pembimbing",
				"content" => "1104101010001-sk-pembimbing.pdf",
				"no" => "1/TA/II/2020",
				"tgl" => "2020-06-27",
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 15:02:31",
				"updated_at" => "2020-06-27 15:11:00",
			),
			array(
				"id" => 56,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "undangan-sempro",
				"display_name" => "Undangan Seminar Proposal",
				"content" => "1104101010001-undangan-sempro.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-28 18:33:23",
				"updated_at" => "2020-06-30 12:03:25",
			),
			array(
				"id" => 22,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "file",
				"name" => "stpd",
				"display_name" => "Surat Tugas Pengambilan Data",
				"content" => "1104101010001-stpd.pdf",
				"no" => "1/TA/II/2020",
				"tgl" => "2020-06-27",
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 16:49:00",
				"updated_at" => "2020-06-27 17:01:41",
			),
			array(
				"id" => 23,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "jumlah-asistensi",
				"display_name" => "Jumlah Asistensi",
				"content" => "8",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 20:27:31",
				"updated_at" => "2020-06-27 20:27:31",
			),
			array(
				"id" => 24,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "masa-pembimbingan-proposal",
				"display_name" => "Masa Pembimbingan Proposal",
				"content" => "3",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 20:27:31",
				"updated_at" => "2020-06-27 20:27:31",
			),
			array(
				"id" => 25,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "lembar-asistensi",
				"display_name" => "Lembar Asistensi",
				"content" => "1104101010001-lembar-asistensi.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 22:47:21",
				"updated_at" => "2020-07-05 10:28:09",
			),
			array(
				"id" => 26,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "draft-buku-proposal",
				"display_name" => "Draft Buku Proposal",
				"content" => "1104101010001-draft-buku-proposal.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-27 22:47:21",
				"updated_at" => "2020-07-05 10:28:09",
			),
			array(
				"id" => 52,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "jam-seminar",
				"display_name" => "Jam Seminar",
				"content" => "14:00",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-28 15:10:14",
				"updated_at" => "2020-07-05 10:28:09",
			),
			array(
				"id" => 54,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "tempat-seminar",
				"display_name" => "Tempat Seminar",
				"content" => "Ruang Seminar 1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-28 15:10:14",
				"updated_at" => "2020-07-05 10:28:09",
			),
			array(
				"id" => 58,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-1",
				"display_name" => "Peserta Seminar 1",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 59,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-2",
				"display_name" => "Peserta Seminar 2",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 60,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-3",
				"display_name" => "Peserta Seminar 3",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 61,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-4",
				"display_name" => "Peserta Seminar 4",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 62,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-5",
				"display_name" => "Peserta Seminar 5",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 63,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-6",
				"display_name" => "Peserta Seminar 6",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 64,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-7",
				"display_name" => "Peserta Seminar 7",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 65,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-8",
				"display_name" => "Peserta Seminar 8",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 66,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-9",
				"display_name" => "Peserta Seminar 9",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 67,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "peserta-seminar-10",
				"display_name" => "Peserta Seminar 10",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:14:12",
				"updated_at" => "2020-06-29 10:14:12",
			),
			array(
				"id" => 68,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "berita-acara-seminar-proposal",
				"display_name" => "Berita Acara Seminar Proposal",
				"content" => "1104101010001-berita-acara-seminar-proposal.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:29:31",
				"updated_at" => "2020-06-29 11:10:27",
			),
			array(
				"id" => 69,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "buku-proposal",
				"display_name" => "Buku Proposal",
				"content" => "1104101010001-buku-proposal.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 10:29:31",
				"updated_at" => "2020-06-29 11:10:27",
			),
			array(
				"id" => 70,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "file",
				"name" => "daftar-hadir-seminar-proposal",
				"display_name" => "Daftar Hadir Seminar Proposal",
				"content" => "1104101010001-daftar-hadir-seminar-proposal.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 11:39:59",
				"updated_at" => "2020-06-29 11:48:41",
			),
			array(
				"id" => 71,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "jumlah-asistensi-2",
				"display_name" => "Jumlah Asistensi Buku TGA",
				"content" => "10",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 12:05:22",
				"updated_at" => "2020-06-29 12:05:22",
			),
			array(
				"id" => 72,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "masa-pembimbingan-buku-tga",
				"display_name" => "Masa Pembimbingan Buku TGA",
				"content" => "2",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 12:05:22",
				"updated_at" => "2020-06-29 12:05:22",
			),
			array(
				"id" => 75,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "ijazah",
				"display_name" => "Ijazah",
				"content" => "1104101010001-ijazah.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "false",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 12:58:59",
				"updated_at" => "2020-06-29 12:58:59",
			),
			array(
				"id" => 76,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "bukti-nilai-toefl",
				"display_name" => "Bukti Nilai Toefl",
				"content" => "1104101010001-bukti-nilai-toefl.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "false",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 12:58:59",
				"updated_at" => "2020-06-29 12:58:59",
			),
			array(
				"id" => 138,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-3",
				"display_name" => "Peserta Sidang 3",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 139,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-4",
				"display_name" => "Peserta Sidang 4",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 141,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-6",
				"display_name" => "Peserta Sidang 6",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 126,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "ketua-penguji-2",
				"display_name" => "Ketua Penguji Sidang Buku TGA",
				"content" => "Dr. Ir. Abdullah, M.Sc.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 16:13:28",
				"updated_at" => "2020-06-29 16:14:08",
			),
			array(
				"id" => 127,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "penguji-1-2",
				"display_name" => "Penguji 1 Sidang Buku TGA",
				"content" => "Dr. Ir. Abdullah, M.Sc.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 16:13:28",
				"updated_at" => "2020-06-29 16:14:21",
			),
			array(
				"id" => 128,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "penguji-2-2",
				"display_name" => "Penguji 2 Sidang Buku TGA",
				"content" => "Dr. Ir. Abdullah, M.Sc.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 16:13:28",
				"updated_at" => "2020-06-29 16:14:30",
			),
			array(
				"id" => 129,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "penguji-3-2",
				"display_name" => "Penguji 3 Sidang Buku TGA",
				"content" => "Dr. Ir. Abdullah, M.Sc.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 16:13:28",
				"updated_at" => "2020-06-29 16:14:41",
			),
			array(
				"id" => 73,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "lembar-asistensi-2",
				"display_name" => "Lembar Asistensi Buku TGA",
				"content" => "1104101010001-lembar-asistensi-2.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 12:29:25",
				"updated_at" => "2020-06-29 16:15:53",
			),
			array(
				"id" => 130,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "jam-sidang",
				"display_name" => "Jam Sidang",
				"content" => "21:09",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 16:13:29",
				"updated_at" => "2020-06-29 16:15:53",
			),
			array(
				"id" => 131,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "tgl-sidang",
				"display_name" => "Tanggal Sidang",
				"content" => "2020-07-01",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 16:13:29",
				"updated_at" => "2020-06-29 16:15:53",
			),
			array(
				"id" => 132,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "tempat-sidang",
				"display_name" => "Tempat Sidang",
				"content" => "Ruang Sidang 1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 16:13:29",
				"updated_at" => "2020-06-29 16:15:53",
			),
			array(
				"id" => 142,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-7",
				"display_name" => "Peserta Sidang 7",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 133,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "sk-penguji-sidang",
				"display_name" => "SK Penguji Sidang",
				"content" => "1104101010001-sk-penguji-sidang.pdf",
				"no" => "1/TA/II/2020",
				"tgl" => "2020-06-30",
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 17:26:47",
				"updated_at" => "2020-06-30 13:12:24",
			),
			array(
				"id" => 134,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "undangan-sidang",
				"display_name" => "Undangan Sidang Buku TGA",
				"content" => "1104101010001-undangan-sidang.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 17:26:47",
				"updated_at" => "2020-06-30 13:12:24",
			),
			array(
				"id" => 135,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "berkas-sidang-lainnya",
				"display_name" => "Berkas Sidang Lainnya",
				"content" => "1104101010001-berkas-sidang-lainnya.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-29 17:26:47",
				"updated_at" => "2020-06-30 13:12:24",
			),
			array(
				"id" => 136,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-1",
				"display_name" => "Peserta Sidang 1",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 137,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-2",
				"display_name" => "Peserta Sidang 2",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 143,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-8",
				"display_name" => "Peserta Sidang 8",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 144,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-9",
				"display_name" => "Peserta Sidang 9",
				"content" => "a-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-06-30 13:57:54",
			),
			array(
				"id" => 146,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "berita-acara-sidang-buku",
				"display_name" => "Berita Acara Sidang Buku",
				"content" => "1104101010001-berita-acara-sidang-buku.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 14:12:25",
				"updated_at" => "2020-06-30 14:38:24",
			),
			array(
				"id" => 147,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "buku-tga",
				"display_name" => "Buku TGA",
				"content" => "1104101010001-buku-tga.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 14:12:25",
				"updated_at" => "2020-06-30 14:38:24",
			),
			array(
				"id" => 160,
				"user_id" => 68,
				"category" => "data_yudisium",
				"type" => "file",
				"name" => "biodata",
				"display_name" => "Biodata",
				"content" => "1104101010001-biodata.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 20:23:02",
				"updated_at" => "2020-06-30 20:25:06",
			),
			array(
				"id" => 161,
				"user_id" => 68,
				"category" => "data_yudisium",
				"type" => "file",
				"name" => "transkrip",
				"display_name" => "Transkrip",
				"content" => "1104101010001-transkrip.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 20:23:02",
				"updated_at" => "2020-06-30 20:25:06",
			),
			array(
				"id" => 162,
				"user_id" => 68,
				"category" => "data_yudisium",
				"type" => "file",
				"name" => "bukti-bebas-lab",
				"display_name" => "Bukti Bebas Lab",
				"content" => "1104101010001-bukti-bebas-lab.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 20:23:02",
				"updated_at" => "2020-06-30 20:25:06",
			),
			array(
				"id" => 148,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "file",
				"name" => "lembar-pengesahan",
				"display_name" => "Lembar Pengesahan",
				"content" => "1104101010001-lembar-pengesahan.zip",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 16:07:20",
				"updated_at" => "2020-06-30 16:41:20",
			),
			array(
				"id" => 163,
				"user_id" => 68,
				"category" => "data_yudisium",
				"type" => "file",
				"name" => "artikel-jim",
				"display_name" => "Artikel JIM",
				"content" => "1104101010001-artikel-jim.pdf",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 20:23:02",
				"updated_at" => "2020-06-30 20:25:06",
			),
			array(
				"id" => 164,
				"user_id" => 68,
				"category" => "data_yudisium",
				"type" => "file",
				"name" => "kelengkapan-dokumen-administrasi-sidang-buku",
				"display_name" => "Kelengkapan Dokumen Administrasi Sidang Buku",
				"content" => "1104101010001-kelengkapan-dokumen-administrasi-sidang-buku.zip",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 20:23:23",
				"updated_at" => "2020-06-30 20:25:06",
			),
			array(
				"id" => 166,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "tahun-masuk",
				"display_name" => "Tahun Masuk",
				"content" => "2016",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 167,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "asal-smta",
				"display_name" => "Asal Smta",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 168,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "tahun-ijazah-smta",
				"display_name" => "Tahun Ijazah Smta",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 169,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "terdaftar-sebagai-mahasiswa",
				"display_name" => "Terdaftar Sebagai Mahasiswa",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 170,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "bekerja",
				"display_name" => "Bekerja",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 171,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "kawin",
				"display_name" => "Kawin",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 172,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "biaya-pendidikan",
				"display_name" => "Biaya Pendidikan",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 173,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "jumlah-saudara-kandung",
				"display_name" => "Jumlah Saudara Kandung",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 174,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "yang-sudah-sarjana",
				"display_name" => "Yang Sudah Sarjana",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 175,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "sedang-kuliah",
				"display_name" => "Sedang Kuliah",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 176,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "sedang-sekolah",
				"display_name" => "Sedang Sekolah",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 177,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "nama-ayah",
				"display_name" => "Nama Ayah",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 178,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "nama-ibu",
				"display_name" => "Nama Ibu",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 179,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "pendidikan-ayah",
				"display_name" => "Pendidikan Ayah",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 180,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "pendidikan-ibu",
				"display_name" => "Pendidikan Ibu",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 181,
				"user_id" => 68,
				"category" => "biodata",
				"type" => "text",
				"name" => "alamat",
				"display_name" => "Alamat",
				"content" => "Test",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-02 12:17:01",
				"updated_at" => "2020-07-02 12:17:01",
			),
			array(
				"id" => 140,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-5",
				"display_name" => "Peserta Sidang 5",
				"content" => "a-11",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-07-02 21:10:37",
			),
			array(
				"id" => 145,
				"user_id" => 68,
				"category" => "data_usul_sidang_buku",
				"type" => "text",
				"name" => "peserta-sidang-10",
				"display_name" => "Peserta Sidang 10",
				"content" => "a1-1",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-06-30 13:57:54",
				"updated_at" => "2020-07-02 21:10:37",
			),
			array(
				"id" => 185,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "co-pembimbing",
				"display_name" => "Nama Co Pembimbing",
				"content" => "Ir. Banta Chairullah M, M.Ing.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-03 10:15:10",
				"updated_at" => "2020-07-03 19:33:47",
			),
			array(
				"id" => 184,
				"user_id" => 68,
				"category" => "data_usul",
				"type" => "text",
				"name" => "pembimbing",
				"display_name" => "Nama Pembimbing",
				"content" => "Ir. Buraida, M.M.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-03 10:15:10",
				"updated_at" => "2020-07-03 11:45:09",
			),
			array(
				"id" => 190,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "ketua-penguji",
				"display_name" => "Pimpinan Seminar",
				"content" => "Dr. Ir. Abdullah, M.Sc.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-05 10:24:35",
				"updated_at" => "2020-07-05 10:25:20",
			),
			array(
				"id" => 191,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "penguji-1",
				"display_name" => "Penguji 1",
				"content" => "Ahmad Reza Kasury, S.T., M.T.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-05 10:24:35",
				"updated_at" => "2020-07-05 10:25:39",
			),
			array(
				"id" => 192,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "penguji-2",
				"display_name" => "Penguji 2",
				"content" => "Alfa Taras Bulba, ST, M.Sc.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-05 10:24:35",
				"updated_at" => "2020-07-05 10:25:48",
			),
			array(
				"id" => 193,
				"user_id" => 68,
				"category" => "data_usul_sempro",
				"type" => "text",
				"name" => "penguji-3",
				"display_name" => "Penguji 3",
				"content" => "Dr. Ir. Alfiansyah Yulianur BC.",
				"no" => NULL,
				"tgl" => NULL,
				"verified" => "true",
				"verification_key" => NULL,
				"created_at" => "2020-07-05 10:24:35",
				"updated_at" => "2020-07-05 10:25:58",
			),
		);

		foreach ($data as $index => $value) {
			DB::table('data')->insert([
				'user_id' => $value['user_id'],
				'category' => $value['category'],
				'type' => $value['type'],
				'name' => $value['name'],
				'display_name' => $value['display_name'],
				'content' => $value['content'],
				'no' => $value['no'],
				'tgl' => $value['tgl'],
				'verified' => $value['verified'],
				'verification_key' => $value['verification_key'],
				'created_at' => $value['created_at'],
				'updated_at' => $value['updated_at']
			]);
		}
    }
};
